In [1]:
import torch
from nanograd.engine import Value
from nanograd.tensor import Tensor

In [2]:
x = Value(-4.0)
print(x.data)
z = 2 * x + 2 + x
print(z.data)
q = z.relu() + z * x
print(q.data)
h = (z * z).relu()
print(h.data)
y = h + q + q * x
print(y.data)
y.backward()
xmg, ymg = x, y
print(xmg.data)
print(ymg.data)

x = torch.Tensor([-4.0]).double()
x.requires_grad = True
print(x.data)
z = 2 * x + 2 + x
print(z.data)
q = z.relu() + z * x
print(q.data)
h = (z * z).relu()
print(h.data)
y = h + q + q * x
print(y.shape)
y.backward()
xpt, ypt = x, y
print(xpt.shape)
print(ypt.shape)

assert ymg.data == ypt.data.item()
assert xmg.grad == xpt.grad.item()

-4.0
-10.0
40.0
100.0
-20.0
-4.0
-20.0
tensor([-4.], dtype=torch.float64)
tensor([-10.], dtype=torch.float64)
tensor([40.], dtype=torch.float64)
tensor([100.], dtype=torch.float64)
torch.Size([1])
torch.Size([1])
torch.Size([1])


In [3]:
x = Value(40)
y = Value(2)
z = x * y
z += 10
z.backward()

In [4]:
z.data

90

In [6]:
x = Tensor(3)
y = Tensor(10)
result = x * y + x
result.backward()
print(result)


Tensor(33, shape=())
