In [1]:
import torch
from nanograd.engine import Value

In [12]:
x = Value(-4.0)
print(x)
z = 2 * x + 2 + x
print(z)
q = z.relu() + z * x
print(q)
h = (z * z).relu()
print(h)
y = h + q + q * x
print(y)
y.backward()
xmg, ymg = x, y
print(xmg)
print(ymg)

x = torch.Tensor([-4.0]).double()
x.requires_grad = True
print(x)
z = 2 * x + 2 + x
print(z)
q = z.relu() + z * x
print(q)
h = (z * z).relu()
print(h)
y = h + q + q * x
print(y.shape)
y.backward()
xpt, ypt = x, y
print(xpt.shape)
print(ypt.shape)

assert ymg.data == ypt.data.item()
assert xmg.grad == xpt.grad.item()

Value(data=-4.0, grad=0)
Value(data=-10.0, grad=0)
Value(data=40.0, grad=0)
Value(data=100.0, grad=0)
Value(data=-20.0, grad=0)
Value(data=-4.0, grad=46.0)
Value(data=-20.0, grad=1)
tensor([-4.], dtype=torch.float64, requires_grad=True)
tensor([-10.], dtype=torch.float64, grad_fn=<AddBackward0>)
tensor([40.], dtype=torch.float64, grad_fn=<AddBackward0>)
tensor([100.], dtype=torch.float64, grad_fn=<ReluBackward0>)
torch.Size([1])
torch.Size([1])
torch.Size([1])
